vim.keymap.set("n", "-", "<cmd>Oil --float<CR>", { desc = "Open Parent Directory in Oil" })
vim.keymap.set("n", "gl", function()
	vim.diagnostic.open_float()
end, { desc = "Diagnostic" })
vim.keymap.set("n", "<leader>cf", function()
	require("conform").format({
		lsp_format = "fallback",
	})
end, { desc = "Code Formating" })
vim.keymap.set("n", "|", "<cmd>vsp<CR>", { desc = "Split vertical buffer" })
vim.keymap.set("n", "\\", "<cmd>sp<CR>", { desc = "Split horizontal buffer" })
vim.keymap.set("n", "<leader>s", "<cmd>w<CR>", { desc = "Save buffer" })
vim.keymap.set("n", "<leader>q", "<cmd>q<CR>", { desc = "Quit buffer" })
vim.keymap.set("n", "<leader>l", "<cmd>ListcharsToggle<CR>", { desc = "Toggle listchars" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Move to left buffer" })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Move to under buffer" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Move to upper buffer" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Move to right buffer" })
vim.keymap.set("n", "<leader>r", ":ReloadAll<CR>", { desc = "Recharger toute la config" })
vim.keymap.set("n", "<leader>ol", "<cmd>Gen<CR>", { desc = "Ollama" })
vim.keymap.set("n", "<leader>gv1", "<cmd>:DiffviewOpen HEAD~1<CR>", { desc = "Diffview Head~1" })
vim.keymap.set("n", "<leader>gv2", "<cmd>:DiffviewOpen HEAD~2<CR>", { desc = "Diffview Head~2" })
vim.keymap.set("n", "<leader>gv3", "<cmd>:DiffviewOpen HEAD~3<CR>", { desc = "Diffview Head~3" })
vim.keymap.set("n", "<leader>gh", "<cmd>:DiffviewFileHistory %<CR>", { desc = "DiffviewiHistory current file" })
vim.keymap.set("n", "<leader>gc", "<cmd>:DiffviewClose<CR>", { desc = "Diffview Close" })
vim.keymap.set("n", "gp", "<cmd>lua require('goto-preview').goto_preview_definition()<CR>", { noremap = true })
